//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse_GUI.WarehouseService {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Title", Namespace="http://schemas.datacontract.org/2004/07/Warehouse_Server")]
    public enum Title : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LotR = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GoT = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CProgramming = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AIBasicApproach = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RemotingForDummies = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WarehouseService.IWarehouseService")]
    public interface IWarehouseService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWarehouseService/getShopRequests", ReplyAction="http://tempuri.org/IWarehouseService/getShopRequestsResponse")]
        System.Collections.Generic.Dictionary<Warehouse_GUI.WarehouseService.Title, int> getShopRequests();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWarehouseService/getShopRequests", ReplyAction="http://tempuri.org/IWarehouseService/getShopRequestsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<Warehouse_GUI.WarehouseService.Title, int>> getShopRequestsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWarehouseServiceChannel : Warehouse_GUI.WarehouseService.IWarehouseService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WarehouseServiceClient : System.ServiceModel.ClientBase<Warehouse_GUI.WarehouseService.IWarehouseService>, Warehouse_GUI.WarehouseService.IWarehouseService {
        
        public WarehouseServiceClient() {
        }
        
        public WarehouseServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WarehouseServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WarehouseServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WarehouseServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.Dictionary<Warehouse_GUI.WarehouseService.Title, int> getShopRequests() {
            return base.Channel.getShopRequests();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<Warehouse_GUI.WarehouseService.Title, int>> getShopRequestsAsync() {
            return base.Channel.getShopRequestsAsync();
        }
    }
}
